### PR TITLE
Skinnydip MMU2 string reduction - for your consideration.

### PR DESCRIPTION
**Pull request by domesticatedviking**
Hi Supermerill -- I have a lot of respect for your contributions to the Slic3r / PrusaSlicer project, and I'm a long way from being an expert like yourself, but I was hoping you might consider including a feature that a lot of MMU2 users have been appreciating -- namely Skinnydip string reduction -- into your build.

You can read some of the conversation the community has been having with Prusa about this feature [here](https://github.com/prusa3d/PrusaSlicer/issues/2385)

This feature started as a python post-processing script, but for the sake of accuracy of the generated output and overall ease of use, I created my own PrusaSlicer fork. From the very beginning my goal has been to get this feature out to as many MMU users as possible, but the learning curve for me has been very steep - I would consider myself to be an intermediate hobbyist, and maintaining builds across multiple platforms is a bit beyond my skill level.

Anyhow, I have managed to integrate this feature into your fork - you'll find a pre-release build for Windows 64  [here](https://github.com/domesticatedviking/PrusaSlicer/releases).

My hope is that you would consider merging this feature. It is becoming pretty well known among MMU users, and I would like to make it easier for them to get it (as well as to expose them to some of the very cool stuff you are doing in Slic3r++)

If there is any way I can support you in doing this, please let me know and I'll do my best.

### CODE REVIEW

**Comment by supermerill** [comment]
hi

You have to refrain from deleting blank lines, it makes it much harder to merge. If you click on "files changes", you will see all these red lines that shouldn't be.

Ideally, it's possible to add a little line of code to disable the ui when there are no wipetower / mmu. Can do that if you don't know to do it (it just moved from tab.cpp to configmanipulation.cpp with prusaslicer 2.1).
You open configmanipulation.cpp::toggle_print_fff_options and add a line, if you read the code it's pretty self-explanatory : foreach(widget) toggle_field(widget, bool_haswipetowerandmmu)

Will merge it with these changes, or later if i have to them myself.

**Comment by domesticatedviking** [comment]
Hey man, really appreciate the response.  I'm a total novice when it comes
to source control, and multi platform C++ is a wicked ambitious project for
my skill level, but I learn fast.
Re the line thing -- yeah, you'd be quite wise to keep me out of your
codebase as much as possible, but I'm super excited that you're interested
in picking this up.

FYI I have binaries for Windows, Linux, and Mac of the skinnydip branch up
here: https://github.com/domesticatedviking/PrusaSlicer/releases/
Would be willing to volunteer to help with builds of your project for
platforms other than Windows  if that were something you had an interest in.

Peace!

**Comment by supermerill** [comment]
If you can make it compile in macos:
 - if a change is needed in the manual for compiling, please edit it & make a pull request.
 - if you want to create a compiled package for the last release, you can, i will put them into the release post.

Ideally, a cloud-based compilation like the one mainline slic3r has setup should be used to remove this burden from me & you. But I don't have the will to do it right now.

**Comment by domesticatedviking** [comment]
> If you can make it compile in macos:
> 
>     * if a change is needed in the manual for compiling, please edit it & make a pull request.

I think the latest manual is quite good.   The only issue I recall running into was the need to compile it against the same SDK version that prusa was using to avoid a problem with a WXwidgets bug on higher versions.

**Pull request closed without merging**
