### PR TITLE
Add lerdge support

### PR DESCRIPTION
**Pull request by guestisp**
Add support for Lerdge board gcodes

### CODE REVIEW

**Comment by supermerill** [comment]
The lerdge motherboard has marlin on it, no?
it's a hardware, not a firmware, or i miss something?

**Comment by guestisp** [comment]
No, it's a proprietary board with a proprietary firmware

It's not 100% compatible with Marlin, that's why i've added it's flavour, it could be useful in the future.

**Comment by supermerill** [comment]
oh, i forgot, can you write some lines about the difference between marlin and lerdge, to be sure i don't have to read all the code to know it the next time (for a wiki, tooltip, or just answring a question) ?

**Comment by guestisp** [comment]
where should I write that ? Keep in mind that I don't know exactly all the differences between both, I have to check every time if I see some anomalis. There is a supported gcode list on the Lerdge website: http://www.lerdge.com/document/Gcode

Lerdge doens't support all marlin gcodes but they support some additional ones that could be used in the future, in example `M860 (Set structure parameters)` to set the bed size and max print height directly from the printer configuration in Slic3r. (just as example)

If not a problem, keep this as fundation for further updates

BUT: saw right now that there is a `time_estimation_compensation` for non-marlin firmwares.
What's the purpose of that ? M203,M204 and so on, aren't enough to estimate printing time ? PrusaSlicer remove that gcodes automatically if Marlin is not used, AFAIK you are still using them.

**Comment by supermerill** [comment]
> where should I write that ? 
you can write it here, as it's already merged. I'll put it in the wiki here.

> Lerdge doens't support all marlin gcodes but they support some additional ones that could be  used in the future, in example M860 (Set structure parameters) to set the bed size and max print height directly from the printer configuration in Slic3r.
You could have added that, see gcode.cpp line 1240 -1270, or gcodewriter.cpp line 46.

> If not a problem, keep this as fundation for further updates
I prefer to not add something if there's no direct usefulness, as it creates useless code that can be forgotten. the gcode_flavor system is a fundation, not an other entry (imo).

> a time_estimation_compensation for non-marlin firmwares.
> What's the purpose of that ?
that's because the time estimation use the marlin algorithm to compute the time. Other firmware will behave differently. that's a poor-man quick fix. See the issue in question (link in release page).

**Comment by guestisp** [comment]
If not useful, feel free to revert back. On my own, i'll try to export the printer structure parameters (M860) from the Printer Configuration when using Lerdge firmware (or reprap)

**Comment by supermerill** [comment]
It's merged, now we have to make the most use of it.

**Comment by supermerill** [comment]
So, how the doc about the M860  is going? What i should write?

**Pull request merged**
